name: Print Info
on:
    pull_request:
        types:
            - opened
        branches:
            - main
            - 'ego-*'   #ergo-aws, ergo-fix-upload etc
            - 'feat/**' #feat/login, feat/login/google 
    workflow_dispatch:
    push:
        branches:
            - main
            - 'ego-*'   #ergo-aws, ergo-fix-upload etc
            - 'feat/**' #feat/login, feat/login/google 
jobs:
    print-info:
        runs-on: ubuntu-latest
        steps:
            - name: Print GitHub context
              run: echo "${{toJson(github)}}"