name: Exercise Workflow
on:
    push: 
        branches: [ "main", "master" ]
    
    pull_request:
        branches: [ "main", "master" ]

jobs:
    build: 
        name: Build Project
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3
            
            -   name: Install NodeJS
                uses: actions/setup-node@v3
                with: 
                    node-version: 18

            -   name: Install Packages
                run: npm ci
            
            -   name: Install Angular CLI
                run: npm install -g @angular/cli
            
            -   name: Install Dependencies
                run: | 
                    sudo apt-get update

            -   name: Build
                run: ng build

            -   name: Upload Artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: dist
                    path: | 
                        dist
                        package.json

            -   name: Print 
                run: ls -la

    test-A:
        name: Run Tests on Ubuntu
        needs: build
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3
            
            -   name: Install NodeJS
                uses: actions/setup-node@v3
                with: 
                    node-version: 18

            -   name: Install Packages
                run: npm ci
            
            -   name: Install Angular CLI
                run: npm install -g @angular/cli
            
            -   name: Install Dependencies
                run: | 
                    sudo apt-get update

            -   name: Run specs tests
                run: | 
                    CHROME_BIN=$(which chromium) ng test --browsers=ChromeHeadless --watch=false
                env: 
                    CHROME_BIN: /usr/bin/chromium-browser

            -   name: Print Hello World
                run: | 
                    echo "Hello World"
                    echo ";)"

    test-B:
        name: Run Tests on Windows
        needs: build
        runs-on: windows-latest
        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3
            
            -   name: Install NodeJS
                uses: actions/setup-node@v3
                with: 
                    node-version: 18

            -   name: Install Packages
                run: npm ci
            
            -   name: Install Angular CLI
                run: npm install -g @angular/cli

            -   name: Run specs tests
                run: | 
                    CHROME_BIN=$(which chromium) ng test --browsers=ChromeHeadless --watch=false
                env: 
                    CHROME_BIN: C:/Program Files/Google/Chrome/Application/chrome.exe

    deploy:
        name: Deploy
        needs: [build, test-A, test-B]
        runs-on: ubuntu-22.04
        steps:
            -   name: Get Build and Tests Artifacts
                uses: actions/download-artifact@v4
                with:
                    name: dist

            -   name: Print
                run: ls



