name: Secrets

on:
  workflow_dispatch:

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret (DON'T DO THIS IN PRODUCTION!)
        run: echo "Your secret is ${{ secrets.JUST_API_KEY }}"
